# Generated by Django 4.1.2 on 2022-10-30 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('telefono', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GYO',
            fields=[
                ('grupo_y_orden', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('modelo_unidad', models.CharField(max_length=15)),
                ('Estado_del_Suscriptor', models.CharField(max_length=40)),
                ('inicio_de_Suscripcion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('suscripcion', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('unidad_Suscripta', models.CharField(max_length=30)),
                ('unidad_Solicitada', models.CharField(max_length=30)),
                ('Fecha_ingreso_Pedido', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Morosidad',
            fields=[
                ('status_cartera', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cantidad_de_cuotas_impagas', models.IntegerField(max_length=3)),
                ('cantidad_de_cuotas_pagas', models.IntegerField(max_length=3)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Govalo.cliente')),
                ('GYO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Govalo.gyo')),
            ],
        ),
    ]
