# Generated by Django 4.1.2 on 2022-10-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Govalo', '0002_cliente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gyo',
            name='Estado_de_Pedido',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobado')], default='P', max_length=1),
        ),
    ]
